[package]
name = "nym-sphinx-types"
version = "0.2.0"
description = "Re-export sphinx packet types"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
#sphinx-packet = { version = "0.1.0" }
sphinx-packet = { git = "https://github.com/nymtech/sphinx.git", branch = "simon/replay_tag"}

#[patch.crates-io]
#sphinx-packet = { path = "../../../../sphinx" }
