[package]
name = "multisig-contract-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-utils = "0.16.0"
cw3 = "1.0.0"
cw3-fixed-multisig = { version = "1.0.0", features = ["library"] }
cw4 = "1.0.0"
cosmwasm-std = "1.0.0"
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
